# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'ChildAddDyNumber.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
'''
    添加
'''

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QFrame, QMessageBox
import os



class CdyNumber(QFrame):
    def __init__(self,obj,excel):
        super(CdyNumber, self).__init__()
        self._main = obj
        self._excel = excel
        self._path = os.getcwd()
        self._file = os.getcwd()+"/"+"dy.txt"
        # 抖音号列表
        self._dy = []

        try:
            with open(self._file, "r") as f:
                text = f.read()
                text = text.split("#")[:-1]
                for t in text:
                    self._dy.append(t)
            # print("dy:",self._dy)
        except Exception:
            with open(self._file, "w") as f:
                pass
                # print(id(self._main))
        self.setupUi()

    def setupUi(self):
        self.setObjectName("frame")
        self.resize(400, 300)
        self.setMinimumSize(QtCore.QSize(400, 300))
        self.setMaximumSize(QtCore.QSize(400, 300))
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(140, 110, 121, 51))
        self.pushButton.setObjectName("pushButton")
        self.DelpushButton = QtWidgets.QPushButton(self)
        self.DelpushButton.setGeometry(QtCore.QRect(140, 220, 121, 51))
        self.DelpushButton.setObjectName("DelpushButton")
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(20, 50, 351, 53))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.widget1 = QtWidgets.QWidget(self)
        self.widget1.setGeometry(QtCore.QRect(20, 162, 351, 51))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.DelLineEdit = QtWidgets.QLineEdit(self.widget1)
        self.DelLineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.DelLineEdit.setObjectName("DelLineEdit")
        self.horizontalLayout_2.addWidget(self.DelLineEdit)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        
        # 添加事件
        self.pushButton.clicked.connect(lambda :self._add())
        # 删除事件
        self.DelpushButton.clicked.connect(lambda :self._del())

    # 写文件
    def _wirte(self):
        with open(self._file, "w") as f:
            for t in self._dy:
                f.write(t)
                f.write("#")
    # 添加事件
    def _add(self):
        text = self.lineEdit.text()
        if text and text not in self._excel.getDyList():
            self._dy.append(text)
            self._main._addcomboBox(text)  # 同步到下拉框
            # self._excel.oldDataSyn()  # 旧数据同步
            # 增加抖音号
            # print("s:",self._main._comboBoxText)
            self._excel.extensionExcel()   # 同步到Excel
            self._main.refresh()  # 刷新

            self._wirte()
            self.lineEdit.setText("")
        else:
            QMessageBox.information(self, "提示", "重复或者为空")
    # 删除事件
    def _del(self):
        c = QMessageBox.warning(self,"警告","一旦删除则无法恢复",QMessageBox.Yes | QMessageBox.No)

        if c == QMessageBox.Yes:
            text = self.DelLineEdit.text()
            try:
                if text and text in self._dy:
                    self._dy.remove(text)
                    self._main._delcomBox(text) # 同步到下拉框
                    # self._excel.oldDataSyn()  # 旧数据同步
                    self._excel.extensionExcel() # 同步到Excel
                    self._wirte()
                    self._main.refresh() # 刷新
                    QMessageBox.information(self, "提示", "{}删除成功".format(text))
                else:
                    QMessageBox.information(self, "提示", "没有此号")
                # print("dy:",self._dy)
                # with open("","r") as f:
                #     f.read()
            except Exception as e:
                # print(e)
                pass
            self.DelLineEdit.setText("")


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "账号窗口"))
        self.pushButton.setText(_translate("self", "添加"))
        self.DelpushButton.setText(_translate("self", "删除"))
        self.label.setText(_translate("self", "抖音号:"))
        self.label_2.setText(_translate("self", "删除账号"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    f = CdyNumber()
    f.show()
    app.exit(app.exec_())